-- The reverse migration restores the original string columns and constraints.
PRAGMA foreign_keys = OFF;
PRAGMA defer_foreign_keys = ON;

CREATE TABLE follow_requests_old AS SELECT id, sender_id, recipient_id, CASE status WHEN 1000 THEN 'PENDING' WHEN 1010 THEN 'ACCEPTED' ELSE 'DECLINED' END AS status, created_at, responded_at FROM follow_requests;
DROP TABLE follow_requests;
CREATE TABLE follow_requests (id TEXT PRIMARY KEY NOT NULL CHECK(length(id) = 36), sender_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, recipient_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','ACCEPTED','DECLINED','CANCELLED')), created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), responded_at TEXT, CHECK(sender_id <> recipient_id), CHECK((status = 'PENDING' AND responded_at IS NULL) OR (status <> 'PENDING' AND responded_at IS NOT NULL)));
INSERT INTO follow_requests SELECT * FROM follow_requests_old; DROP TABLE follow_requests_old;
CREATE UNIQUE INDEX uq_follow_requests_pending ON follow_requests(sender_id, recipient_id) WHERE status = 'PENDING'; CREATE INDEX idx_follow_requests_recipient_status ON follow_requests(recipient_id, status, created_at DESC); CREATE INDEX idx_follow_requests_sender_status ON follow_requests(sender_id, status, created_at DESC);

CREATE TABLE group_invitations_old AS SELECT id, group_id, inviter_id, invited_user_id, CASE status WHEN 1000 THEN 'PENDING' WHEN 1010 THEN 'ACCEPTED' ELSE 'DECLINED' END AS status, created_at, responded_at FROM group_invitations;
DROP TABLE group_invitations;
CREATE TABLE group_invitations (id TEXT PRIMARY KEY NOT NULL CHECK(length(id) = 36), group_id TEXT NOT NULL, inviter_id TEXT NOT NULL, invited_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','ACCEPTED','DECLINED','CANCELLED')), created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), responded_at TEXT, FOREIGN KEY(group_id, inviter_id) REFERENCES group_members(group_id, user_id) ON DELETE CASCADE, CHECK(inviter_id <> invited_user_id), CHECK((status = 'PENDING' AND responded_at IS NULL) OR (status <> 'PENDING' AND responded_at IS NOT NULL)));
INSERT INTO group_invitations SELECT * FROM group_invitations_old; DROP TABLE group_invitations_old;
CREATE UNIQUE INDEX uq_group_invitation_pending ON group_invitations(group_id, invited_user_id) WHERE status='PENDING'; CREATE INDEX idx_group_invitations_invited ON group_invitations(invited_user_id, status, created_at DESC); CREATE INDEX idx_group_invitations_group ON group_invitations(group_id, status, created_at DESC);

CREATE TABLE group_join_requests_old AS SELECT id, group_id, user_id, CASE status WHEN 1000 THEN 'PENDING' WHEN 1010 THEN 'ACCEPTED' ELSE 'DECLINED' END AS status, created_at, responded_at FROM group_join_requests;
DROP TABLE group_join_requests;
CREATE TABLE group_join_requests (id TEXT PRIMARY KEY NOT NULL CHECK(length(id) = 36), group_id TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','ACCEPTED','DECLINED','CANCELLED')), created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), responded_at TEXT, UNIQUE(id, group_id), CHECK((status = 'PENDING' AND responded_at IS NULL) OR (status <> 'PENDING' AND responded_at IS NOT NULL)));
INSERT INTO group_join_requests SELECT * FROM group_join_requests_old; DROP TABLE group_join_requests_old;
CREATE UNIQUE INDEX uq_group_join_request_pending ON group_join_requests(group_id, user_id) WHERE status='PENDING'; CREATE INDEX idx_group_join_requests_group ON group_join_requests(group_id, status, created_at DESC); CREATE INDEX idx_group_join_requests_user ON group_join_requests(user_id, status, created_at DESC);

ALTER TABLE group_members DROP COLUMN status;

CREATE TABLE profiles_old AS SELECT user_id, CASE privacy WHEN 1010 THEN 'PRIVATE' ELSE 'PUBLIC' END AS privacy, nickname, about_me, created_at, updated_at FROM profiles; DROP TABLE profiles;
CREATE TABLE profiles (user_id TEXT PRIMARY KEY NOT NULL REFERENCES users(id) ON DELETE CASCADE, privacy TEXT NOT NULL DEFAULT 'PUBLIC' CHECK(privacy IN ('PUBLIC','PRIVATE')), nickname TEXT COLLATE NOCASE UNIQUE CHECK(nickname IS NULL OR length(trim(nickname)) BETWEEN 3 AND 40), about_me TEXT CHECK(about_me IS NULL OR length(about_me) <= 2000), created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')));
INSERT INTO profiles SELECT * FROM profiles_old; DROP TABLE profiles_old; CREATE INDEX idx_profiles_privacy ON profiles(privacy);

CREATE TABLE posts_old AS SELECT id, author_id, group_id, content, CASE privacy WHEN 1000 THEN 'PUBLIC' WHEN 1010 THEN 'FOLLOWERS' ELSE CASE WHEN group_id IS NULL THEN 'PRIVATE' ELSE 'GROUP' END END AS privacy, created_at, updated_at, is_active FROM posts; DROP TABLE posts;
CREATE TABLE posts (id TEXT PRIMARY KEY NOT NULL CHECK(length(id) = 36), author_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT, group_id TEXT REFERENCES groups(id) ON DELETE CASCADE, content TEXT NOT NULL DEFAULT '' CHECK(length(content) <= 10000), privacy TEXT NOT NULL CHECK(privacy IN ('PUBLIC','FOLLOWERS','PRIVATE','GROUP')), created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), is_active BOOLEAN NOT NULL DEFAULT TRUE CHECK(is_active IN (FALSE, TRUE)), CHECK((group_id IS NULL AND privacy IN ('PUBLIC','FOLLOWERS','PRIVATE')) OR (group_id IS NOT NULL AND privacy = 'GROUP')));
INSERT INTO posts SELECT * FROM posts_old; DROP TABLE posts_old; CREATE INDEX idx_posts_author_feed ON posts(author_id, created_at DESC) WHERE is_active = 1; CREATE INDEX idx_posts_group_feed ON posts(group_id, created_at DESC) WHERE is_active = 1; CREATE INDEX idx_posts_public_feed ON posts(privacy, created_at DESC) WHERE is_active = 1;

CREATE TABLE event_attendees_old AS SELECT event_id, group_id, user_id, CASE response WHEN 1000 THEN 'GOING' ELSE 'NOT_GOING' END AS response, responded_at FROM event_attendees; DROP TABLE event_attendees;
CREATE TABLE event_attendees (event_id TEXT NOT NULL, group_id TEXT NOT NULL, user_id TEXT NOT NULL, response TEXT NOT NULL CHECK(response IN ('GOING','NOT_GOING')), responded_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), PRIMARY KEY(event_id, user_id), FOREIGN KEY(event_id, group_id) REFERENCES group_events(id, group_id) ON DELETE CASCADE, FOREIGN KEY(group_id, user_id) REFERENCES group_members(group_id, user_id) ON DELETE CASCADE) WITHOUT ROWID;
INSERT INTO event_attendees SELECT * FROM event_attendees_old; DROP TABLE event_attendees_old; CREATE INDEX idx_event_attendees_user ON event_attendees(user_id, event_id);

CREATE TABLE notifications_old AS SELECT id, recipient_id, actor_id, CASE type WHEN 1010 THEN 'GROUP_INVITATION' WHEN 1020 THEN 'GROUP_JOIN_REQUEST' WHEN 1030 THEN 'GROUP_EVENT_CREATED' ELSE 'FOLLOW_REQUEST' END AS type, follow_request_id, group_invitation_id, group_join_request_id, group_event_id, post_id, comment_id, is_read, created_at, read_at FROM notifications; DROP TABLE notifications;
CREATE TABLE notifications (id TEXT PRIMARY KEY NOT NULL CHECK(length(id) = 36), recipient_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, actor_id TEXT REFERENCES users(id) ON DELETE SET NULL, type TEXT NOT NULL CHECK(type IN ('FOLLOW_REQUEST','FOLLOW_ACCEPTED','GROUP_INVITATION','GROUP_JOIN_REQUEST','GROUP_EVENT_CREATED','POST_REACTION','COMMENT_REACTION','COMMENT','NEW_FOLLOWER')), follow_request_id TEXT REFERENCES follow_requests(id) ON DELETE CASCADE, group_invitation_id TEXT REFERENCES group_invitations(id) ON DELETE CASCADE, group_join_request_id TEXT REFERENCES group_join_requests(id) ON DELETE CASCADE, group_event_id TEXT REFERENCES group_events(id) ON DELETE CASCADE, post_id TEXT REFERENCES posts(id) ON DELETE CASCADE, comment_id TEXT REFERENCES comments(id) ON DELETE CASCADE, is_read INTEGER NOT NULL DEFAULT 0 CHECK(is_read IN (0,1)), created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), read_at TEXT, CHECK((is_read = 0 AND read_at IS NULL) OR (is_read = 1 AND read_at IS NOT NULL)));
INSERT INTO notifications SELECT * FROM notifications_old; DROP TABLE notifications_old; CREATE INDEX idx_notifications_unread ON notifications(recipient_id, is_read, created_at DESC);

PRAGMA foreign_keys = ON;
